### ISSUE TITLE
请问为什么Loss基本不下降

### ISSUE THREAD

**Issue by SongDark** [Runist/MAML-keras#4]
数据集就是Omniglot，直接运行代码。
与readme中的图很不一样。

![image](https://user-images.githubusercontent.com/33924029/118254433-ac837300-b4dd-11eb-9eec-0ded614b3d51.png)

**Comment by Runist** [comment]
你的batch size和Input shape有修改过吗？maml训练是比较敏感的，我测试了其他batch和lr，在config.py的默认配置是每次都能收敛的。另外我是将smooth调成了1.0，因为每个step的loss都记录波动是很大的，而且你这个才刚开始没多久，基本上step要到1M左右才能慢慢看到收敛的趋势。

**Comment by SongDark** [comment]
所有参数都没有改动过，直接run的。
跑了3M，Loss先降后升，然后基本收敛。（与你的readme中截图似乎不太一致）
想问下，怎样评估MAML已经训练好了呢？
![image](https://user-images.githubusercontent.com/33924029/118387722-9f3bc500-b652-11eb-8cf0-8427a4e320d3.png)

**Comment by Runist** [comment]
> 所有参数都没有改动过，直接run的。
> 跑了3M，Loss先降后升，然后基本收敛。（与你的readme中截图似乎不太一致）
> 想问下，怎样评估MAML已经训练好了呢？
> ![image](https://user-images.githubusercontent.com/33924029/118387722-9f3bc500-b652-11eb-8cf0-8427a4e320d3.png)
将你训练好的模型用evaluate.py运行，对比随机初始化的权重，maml的权重只需要几次迭代就可以收敛说明就训练好了。其实对比随机初始化是肯定会不差的，后期我会用cifar10或者是mnist来对比测试。

**Comment by SongDark** [comment]
reply：将你训练好的模型用evaluate.py运行，对比随机初始化的权重，maml的权重只需要几次迭代就可以收敛说明就训练好了。其实对比随机初始化是肯定会不差的，后期我会用cifar10或者是mnist来对比测试。

放进evaluate.py运行是比随机初始化更差的。
我决定再跑一次试试。
![image](https://user-images.githubusercontent.com/33924029/118394674-8ba35500-b678-11eb-89d2-212da175b616.png)

另外我在运行你代码的时候遇到个问题：图像转灰度图后，shape会变成 (bs, 28, 28)，因此会报错：
ValueError: Input 0 of layer sequential is incompatible with the layer: : expected min_ndim=4, found ndim=3. Full shape received: (5, 28, 28)
所以我加了expand_dims。
![image](https://user-images.githubusercontent.com/33924029/118394600-4121d880-b678-11eb-949e-7966024ab447.png)

**Comment by Runist** [comment]
你等一等哈，我先复现一下你的问题。

**Comment by Runist** [comment]
> reply：将你训练好的模型用evaluate.py运行，对比随机初始化的权重，maml的权重只需要几次迭代就可以收敛说明就训练好了。其实对比随机初始化是肯定会不差的，后期我会用cifar10或者是mnist来对比测试。
> 
> 放进evaluate.py运行是比随机初始化更差的。
> 我决定再跑一次试试。
> ![image](https://user-images.githubusercontent.com/33924029/118394674-8ba35500-b678-11eb-89d2-212da175b616.png)
> 
> 另外我在运行你代码的时候遇到个问题：图像转灰度图后，shape会变成 (bs, 28, 28)，因此会报错：
> ValueError: Input 0 of layer sequential is incompatible with the layer: : expected min_ndim=4, found ndim=3. Full shape received: (5, 28, 28)
> 所以我加了expand_dims。
> ![image](https://user-images.githubusercontent.com/33924029/118394600-4121d880-b678-11eb-949e-7966024ab447.png)

我这边也出现了loss上升的情况了，我看看是什么问题

**Comment by Runist** [comment]
我重现了问题，一开始以为时meta_weights在内部更新的时候被修改了。后面发现还是学习率的问题，把outer lr 调成0.0001，inner lr调成0.02就好了

**Comment by SongDark** [comment]
reply: 我重现了问题，一开始以为时meta_weights在内部更新的时候被修改了。后面发现还是学习率的问题，把outer lr 调成0.0001，inner lr调成0.02就好了

调整后确实降了。
感谢耐心解答。
